### PR TITLE
fix typos and add prerender.entries

### PR DESCRIPTION
**Pull request by JaKXz**
Continuing thoughts from #10, this PR:
- updates all svelte dependencies [and nearly gets the build passing!]
- fixes a typo in the `/blog/category/page/[page]` route
- and adds all the routes that aren't explicitly pre-rendered to sveltekit's prerendering... 
- [and I apologize for vscode auto-formatting the files touched]

<details>
<summary>

~~but... here's a new / more inscrutable error we're still seeing:~~ solved this error in my linked PR below by removing what look like errant routes and calls.

</summary>

```
/Users/jasonkurian/src/github.com/josh-collinsworth/sveltekit-blog-starter/node_modules/undici/lib/fetch/body.js:271
        throw new TypeError('The body has already been consumed.')
              ^

TypeError: The body has already been consumed.
    at consumeBody (/Users/jasonkurian/src/github.com/josh-collinsworth/sveltekit-blog-starter/node_modules/undici/lib/fetch/body.js:271:15)
    at consumeBody.next (<anonymous>)
    at Response.arrayBuffer (/Users/jasonkurian/src/github.com/josh-collinsworth/sveltekit-blog-starter/node_modules/undici/lib/fetch/body.js:353:24)
    at visit (file:///Users/jasonkurian/src/github.com/josh-collinsworth/sveltekit-blog-starter/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:257:69)
```

</details>

### CODE REVIEW

**Comment by JaKXz** [comment]
Here's the PR on my fork that got everything working, but, I'd love to double check that I didn't remove anything that's actually necessary: https://github.com/JaKXz/jakxz.github.io/pull/23

**Comment by josh-collinsworth** [comment]
I'd like to know a little more about the problem this PR is solving, if you're up for an explainer. I can see it converts some `server` files to `page.server`, and adds `config.prerender` routes, but I think I could use some help understanding what the core issue this all solves is. It _seems_ like the current way it's working is doing all right, but I think I'm maybe not running into the same prerendering issues you might have been? I'd love to understand more.

**Comment by JaKXz** [comment]
@josh-collinsworth are you seeing this build error on the latest `main`? Maybe your local working state is different than what's committed?

```
file:///Users/jasonkurian/src/github.com/josh-collinsworth/sveltekit-blog-starter/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:433
		throw new Error(
		      ^

Error: The following routes were marked as prerenderable, but were not prerendered because they were not found while crawling your app:
  - api/posts/category/[category],  - api/posts/page/[page],  - blog/category/page/[page],  - blog/category/[category]/page,  - blog/category/[category]/page/[page],  - blog/page/[page]

See https://kit.svelte.dev/docs/page-options#prerender-troubleshooting for info on how to solve this
    at prerender (file:///Users/jasonkurian/src/github.com/josh-collinsworth/sveltekit-blog-starter/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:433:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by josh-collinsworth** [comment]
@JaKXz No, the build seems to be working fine for me as of last night, though I did do some other updates as well. Maybe I accidentally either fixed the issue a different way, or waited long enough that it resolved itself?

**Comment by JaKXz** [comment]
🤔 I just did a fresh clone and `npm i` (and it still failed)... curious what's different...

**Comment by josh-collinsworth** [comment]
@JaKXz Ahhhh I think it finally bit me after updating SvelteKit again. I just pushed a new version that implements some of the fixes from your PR above. 🙌

**Comment by JaKXz** [comment]
Awesome! I'll close this :)

**Pull request closed without merging**
